# Generated by Django 2.2.4 on 2019-08-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_resposavel', models.CharField(max_length=255, verbose_name='nome_resposavel')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('Nome_ong', models.CharField(max_length=50, verbose_name='Nome_ong')),
                ('str_cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('horario_de_funcionamento', models.CharField(max_length=255, verbose_name='horario_de_funcionamento')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='E-mail')),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
